name: bu_buddy
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0


#--------------PACKAGES------------------#

dependencies:
  flutter:
    sdk: flutter

  #-------------UTILITY PACKAGES------------------#

  #Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3
  smooth_page_indicator: ^1.2.0+3
  shimmer: ^3.0.0


  #ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


  # State Management
#  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^3.12.1
  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.3.0


#  google_maps_flutter: ^2.10.0
  flutter_datetime_picker: ^1.5.1

  geolocator: ^13.0.2  # Downgrade to a version compatible with geolocator_android 3.2.1
  geolocator_android: ^4.6.1
  #  google_places_autocomplete: ^0.0.4
#  geolocator: ^8.2.0
  google_maps_flutter: ^2.0.6
  google_places_autocomplete_flutter: ^1.0.6  # Updated to the latest version
  get: ^4.6.5
  flutter_spinkit: ^5.1.0  # Add this line

  flutter_animate: ^4.2.0
  glassmorphism: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.3
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.1
  path: ^1.8.3
  dart_webrtc: ^1.5.3
  google_fonts: ^6.2.1
  share_handler: ^0.0.22


#-------------./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  #-------------LOCAL ASSETS------------------#

  assets:
    - assets/logos/
    - assets/images/
    - assets/images/content/
    - assets/images/selection_menu/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/icons/brands/

  #-------------LOCAL FONTS------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
