// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvCctSjunHjo8-DSUdq2RE3_e-Kkh7Teg',
    appId: '1:679842035589:android:21d94ed28cf5c06d36f6ec',
    messagingSenderId: '679842035589',
    projectId: 'bubuddy-11b4c',
    storageBucket: 'bubuddy-11b4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYUvjajm8LBwtD-Wp1RW7cGy4IAfj5XIY',
    appId: '1:679842035589:ios:a5814251f169174636f6ec',
    messagingSenderId: '679842035589',
    projectId: 'bubuddy-11b4c',
    storageBucket: 'bubuddy-11b4c.firebasestorage.app',
    androidClientId: '679842035589-pouhf7qr0urv1fh191kkghmshdjvo2f3.apps.googleusercontent.com',
    iosClientId: '679842035589-ehvbj4efchuecisb2nk7rjpi8u8e7cq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.buBuddy',
  );

}